---
- hosts: vm1
  gather_facts: false
  tasks:
    - name: Installing packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        install_recommends: no
      loop:
        - redis
        - libssl1.0-dev
        - npm
        - libjpeg-turbo8-dev
        - libgdal-dev
        - libreadline-dev
        - llvm
        - libncurses5-dev
        - tk-dev
        - libffi-dev
        - build-essential
        - postgis
        - python3-psycopg2
    - name: Checking out pyenv
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: $HOME/.pyenv
    - name: Checking out virtualenv pyenv plugin
      git:
        repo: https://github.com/pyenv/pyenv-virtualenv.git
        dest: $HOME/.pyenv/plugins/pyen-virtualenv
    - name: Defining environment variables for pyenv
      blockinfile:
        path: $HOME/.profile
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
    - name: Adding pyenv init to the shell
      blockinfile:
        path: $HOME/.bashrc
        block: |
          if command -v pyenv 1>/dev/null 2>&1; then
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
          fi
    - name: Installing python 3.5.4
      command: $HOME/.pyenv/bin/pyenv install 3.5.4
      args:
        chdir: /vagrant
    - name: Creating tesseract DB
      become: true
      postgresql_db:
        name: tesseract
    - name: Setup project pyenv
      command: $HOME/.pyenv/bin/pyenv local 3.5.4
      args:
        chdir: /vagrant
    - name: Creating virtualenv
      command: $HOME/.pyenv/bin/pyenv virtualenv smilecheck
      args:
        chdir: /vagrant
    - name: Activating smilecheck virtualenv
      command: $HOME/.pyenv/bin/pyenv activate smilecheck
      args:
        chdir: /vagrant
    - name: Installing python project dependencies
      pip:
        chdir: /vagrant/scc-api
        requirements: requirements.txt
