---
- hosts: vm1
  tasks:
    - include_role:
        name: ansible-pyenv
      vars:
        pyenv_init_shell: true
        pyenv_pyton_versions:
          - "3.5.4"
    - name: Installing packages
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        install_recommends: no
      loop:
        - redis
        - libssl1.0-dev
        - npm
        - libjpeg-turbo8-dev
        - libgdal-dev
        - libreadline-dev
        - llvm
        - libncurses5-dev
        - tk-dev
        - libffi-dev
        - build-essential
        - postgresql
        - postgis
        - python-psycopg2
        - python-bz2file
    - name: Starting PostreSQL service
      service:
        name: postgresql
        state: started
    - name: Creating tesseract DB
      become: true
      postgresql_db:
        name: tesseract
    - name: Setup project pyenv
      command: $HOME/.pyenv/bin/pyenv local 3.5.4
      args:
        chdir: /vagrant
    - name: Creating virtualenv
      command: $HOME/.pyenv/bin/pyenv virtualenv smilecheck
      args:
        chdir: /vagrant
    - name: Activating smilecheck virtualenv
      command: $HOME/.pyenv/bin/pyenv activate smilecheck
      args:
        chdir: /vagrant
    - name: Installing python project dependencies
      pip:
        chdir: /vagrant/scc-api
        requirements: requirements.txt
